ALTER TABLE roles
  ADD COLUMN IF NOT EXISTS descricao VARCHAR(280),
  ADD COLUMN IF NOT EXISTS tipo_role VARCHAR(40),
  ADD COLUMN IF NOT EXISTS regras TEXT,
  ADD COLUMN IF NOT EXISTS aviso_fixado VARCHAR(180);
